server:
  port: 8080
dubbo:
  application:
    name: member
  protocol:
    port: 20880
    name: dubbo
  registry:
    address: zookeeper://192.168.0.162:2181

#  ――――――――――――――――
#  版权声明：本文为CSDN博主「佘雷铭的博客」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
#  原文链接：https://blog.csdn.net/qq_29077619/article/details/89675370